### PR TITLE
Brands responsive

### PR DESCRIPTION
**Pull request by MarekAkram**

### CODE REVIEW

**Comment by GiedreRag** [comment]
Kur ikelei 6 images, i alt="", tarp kabuciu irasyk po viena zodi, kaip ta foto apibudintum, jos pavadinima, tarkim i pirma irasyk Story, i antra img irasyk AirTrack, trecia ZazzleMedia ir taip toliau.

**Review by TadasRup — CHANGES_REQUESTED** [review]
Remove useless classes and fix H4,H2

**Comment by GiedreRag** [comment]
Add "responsive" in the tittle, next to "Brands". Has to be "Brands responsive".

**Review by GiedreRag — DISMISSED** [review]

**Review by TadasRup — APPROVED** [review]
good

**Review by Vilteee — APPROVED** [review]

**Review by Vilteee — APPROVED** [review]

**Review by TadasRup — APPROVED** [review]

**Review by AndriusCa — APPROVED** [review]

**Pull request merged**
