### PR TITLE
Header responsive

### PR DESCRIPTION
**Pull request by TadasRup**
Header responsive and template

### CODE REVIEW

**Comment by GiedreRag** [comment]
Where is <a, do not use all letters in capital, only first word start with capital letter, the rest lowercase.

**Comment by TadasRup** [comment]
> Where is <a, do not use all letters in capital, only first word start with capital letter, the rest lowercase.

fixed, mam

**Comment by GiedreRag** [comment]
no :)) you still need to write full information: Contact today

**Comment by TadasRup** [comment]
> no :)) you still need to write full information: Contact today

fixed

**Review by GiedreRag — APPROVED** [review]

**Review by MarekAkram — APPROVED** [review]

**Review by Vilteee — APPROVED** [review]

**Pull request merged**
